//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hikayeyaziyoruz.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hikayeyaziyoruz.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A common story writing platform for people unaware of each other..
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main İdea.
        /// </summary>
        public static string af {
            get {
                return ResourceManager.GetString("af", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start writing stories?.
        /// </summary>
        public static string basla {
            get {
                return ResourceManager.GetString("basla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We write stories.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this?.
        /// </summary>
        public static string bune {
            get {
                return ResourceManager.GetString("bune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer who started the story.
        /// </summary>
        public static string byaz {
            get {
                return ResourceManager.GetString("byaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Stories.
        /// </summary>
        public static string eh {
            get {
                return ResourceManager.GetString("eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text you want to add.
        /// </summary>
        public static string ekl {
            get {
                return ResourceManager.GetString("ekl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string ekt {
            get {
                return ResourceManager.GetString("ekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string gr {
            get {
                return ResourceManager.GetString("gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Name.
        /// </summary>
        public static string hikad {
            get {
                return ResourceManager.GetString("hikad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Story.
        /// </summary>
        public static string hikek {
            get {
                return ResourceManager.GetString("hikek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Tip.
        /// </summary>
        public static string hiktur {
            get {
                return ResourceManager.GetString("hiktur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First episode.
        /// </summary>
        public static string ilkbol {
            get {
                return ResourceManager.GetString("ilkbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string kayit {
            get {
                return ResourceManager.GetString("kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string kula {
            get {
                return ResourceManager.GetString("kula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string mt {
            get {
                return ResourceManager.GetString("mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text editor.
        /// </summary>
        public static string my {
            get {
                return ResourceManager.GetString("my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of readings.
        /// </summary>
        public static string oks {
            get {
                return ResourceManager.GetString("oks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story creation page.
        /// </summary>
        public static string ols {
            get {
                return ResourceManager.GetString("ols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string sf {
            get {
                return ResourceManager.GetString("sf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Stories.
        /// </summary>
        public static string sonhik {
            get {
                return ResourceManager.GetString("sonhik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        public static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stories.
        /// </summary>
        public static string tumh {
            get {
                return ResourceManager.GetString("tumh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Page.
        /// </summary>
        public static string us {
            get {
                return ResourceManager.GetString("us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-members can not write text and comments.
        /// </summary>
        public static string uya {
            get {
                return ResourceManager.GetString("uya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string uyeol {
            get {
                return ResourceManager.GetString("uyeol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string yl {
            get {
                return ResourceManager.GetString("yl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string yr {
            get {
                return ResourceManager.GetString("yr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment.
        /// </summary>
        public static string yrm {
            get {
                return ResourceManager.GetString("yrm", resourceCulture);
            }
        }
    }
}
