// <auto-generated />
namespace hikayeyaziyoruz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class anametinskullaniciAdi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anametinskullaniciAdi));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141055520_anametinskullaniciAdi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
